### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by duyve** [Moerill/token-mold#131]
Looking to make a few small contributions. Have a branch I would like to push up to get a PR going, but it seems like new branch creation is locked down.

**Comment by Moerill** [comment]
Hi, 
awesome and thank you!
Currently @Geekswordsman is the maintainer of this project, so i'll leave the final decision to them. But i'd suggest either opening a new issue or using this one for a quick overview of your suggested contributions and to be able to discuss them.

As for the branch creation: 
Since the last PRs some time ago i haven't changed a thing. You should be able to use the github UI above to create a pull request from your fork. If not, please post the complete error message here.
