### ISSUE TITLE
Lot of errors thrown in the console

### ISSUE THREAD

**Issue by DarKDinDoN** [Moerill/token-mold#22]
Hello,

Thx for this awesome module.
When opening up a game, I get a lot of error messages in the console:

```javascript
foundry.js:2213 TypeError: Cannot read property 'data' of null
    at o._setCreatureSize (token-mold.js:528)
    at o._setTokenData (token-mold.js:251)
    at token-mold.js:238
    at Function._call (foundry.js:2210)
    at Function.call [as __furnace_original_call] (foundry.js:2195)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at Scene.createEmbeddedEntity (foundry.js:9963)
    at multilevel.js:427
```

Might be because of this module but not sure: https://github.com/grandseiken/foundryvtt-multilevel-tokens

**Comment by Moerill** [comment]
If you don't know if its because of that module, how about disabling it and checkin if the error still exists? ;)
would help a lot!

**Comment by DarKDinDoN** [comment]
You are right. Sorry.
Yep that's a compatibility issue with: https://github.com/grandseiken/foundryvtt-multilevel-tokens

**Comment by Moerill** [comment]
As far as i can see it it doesn't disturb functionality of both modules. Which is good!

Having said that:  the only thing i can do from my side is reducing the amount of errors, but not removing them completly, since the other module seems to delete some attribute at some arbitrary point while token-mold is doing its computations....
created an issue on the other github asking for help.
https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/2

**Comment by Moerill** [comment]
i think this is fixed now?
