### ISSUE TITLE
importing tokens w/ Quick Encounters are very tiny.

### ISSUE THREAD

**Issue by jakvike** [Moerill/token-mold#59]
**Describe the bug**
After clicking 'Add Quick Encounter to Combat Tracker" from the Quick Encounter journal entry.  The tokens are imported as very tiny tokens.  This does not occur with Token Mold module disabled. 

**Expected behavior**
The tokens should be imported based on what they were imported before adding them.

**Module incompatibilities**
Quick Encounters module

**Screenshots/GIFs/Videos**
> A picture is worth a thousand words.
![image](https://user-images.githubusercontent.com/1852180/94065016-27154c00-fdb0-11ea-9c19-7641ca5399c0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - FVTT Version 0.6.6
 - Module version  TM 2.10.0, QE 0.4.1

**Comment by Moerill** [comment]
Yes, there is a slight incompatibility, which can easily be fixed from user side:
- Either you create your encounter using token mold, save it, and when you add it to the map, you just deactivate token molds features. (Which are not needed anymore, since you already put your tokens into a mold before, no reason to keep token molds mold features active)
- Or you create your encounters with token mold disabled, then when you start the encounter you have token mold enabled and everything will be put into its mold.

Providing a fix from the module side is imo not ideal and can only be "wrong", since both options i suggested are valid ways to think about it, and i do not want to force one over the other.

**Comment by jakvike** [comment]
I humbly and respectfully disagree.  This is bad user experience, IMO, specifically during game play. I shouldn't need to enable or disable a module, which refreshes everyone, for the first suggestion.  Concerning the second suggestion, yes this is feasible. However, the intent for these two modules is to save time for the DM/the user. Sorry I am a believer that if you waste a clients time, you fail as a business. I would appreciate it if you could figure out a way to fix this, so they play nice together.

**Comment by Moerill** [comment]
Its not about disabling the module, its about using the quick settings token mold provides to stop overwriting stuff, which is like one click. and no refresh for anyone involved.

**Comment by Moerill** [comment]
> Sorry I am a believer that if you waste a clients time, you fail as a business.

I am no business i am doing this in my free time for fun and not getting any value out of it besides very rare nice words.

**Comment by Moerill** [comment]
And finally i am not sure what i'd want to change.
In the end both modules do what they're supposed to do: Token Mold applies settings to tokens, if you set it up to do so and quick encounter creates tokens. Just like one would expect.

Changing this from a programming standpoint does imply doing some annoying and possibly buggy workaround solution, which i really do not want to do, since its just 1 to 3 clicks to make it work.

**Comment by jakvike** [comment]
I respect your decision. However, I do disagree. I believe if it is a buggy hack then it seems the application may need refactoring.  I have ran into multiple issues with Token Mold and other modules.  So it isnt just this instance. For instance, I had an issue with Forien's Quick Scene. 

Again, I respect your decision.  I truly understand and appreciate your time working on this module, as well as, the others.

**Comment by Moerill** [comment]
Talked with QuickEncounters creator and we decided to fix it on his/her end:
https://github.com/opus1217/quick-encounters/blob/v0.5.0/CHANGELOG.md#v050
(though i may end up adapting to that change)
